# Generated by Django 5.2.16 on 2026-07-12 20:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_assigned', models.DecimalField(blank=True, decimal_places=2, help_text='Required only for quantified items. Must be > 0.', max_digits=12, null=True)),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'item_assignments',
            },
        ),
        migrations.CreateModel(
            name='EventItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('quantity_total', models.DecimalField(blank=True, decimal_places=2, help_text='NULL means binary item (no quantity).', max_digits=12, null=True)),
                ('unit', models.CharField(blank=True, choices=[('kg', 'Kilogramos'), ('g', 'Gramos'), ('liters', 'Litros'), ('ml', 'Mililitros'), ('pieces', 'Piezas'), ('packages', 'Paquetes'), ('bags', 'Bolsas'), ('boxes', 'Cajas'), ('cans', 'Latas'), ('bottles', 'Botellas'), ('jugs', 'Garrafones'), ('trays', 'Charolas'), ('dozens', 'Docenas')], help_text='Required only if quantity_total is set.', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_items', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='events.event')),
            ],
            options={
                'db_table': 'event_items',
            },
        ),
    ]
