# Generated by Django 5.2.16 on 2026-07-12 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('moderation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventitem',
            name='source_suggestion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_item', to='moderation.itemsuggestion'),
        ),
        migrations.AddField(
            model_name='itemassignment',
            name='cancelled_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemassignment',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='items.eventitem'),
        ),
        migrations.AddField(
            model_name='itemassignment',
            name='purchased_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='eventitem',
            index=models.Index(fields=['event'], name='event_items_event_idx'),
        ),
        migrations.AddIndex(
            model_name='itemassignment',
            index=models.Index(fields=['item'], name='item_assignments_item_idx'),
        ),
        migrations.AddIndex(
            model_name='itemassignment',
            index=models.Index(fields=['user'], name='item_assignments_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='itemassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('cancelled_at__isnull', True)), fields=('item', 'user'), name='item_assignments_item_user_key'),
        ),
    ]
