# Generated by Django 5.2.16 on 2026-07-12 20:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('quantity_total', models.DecimalField(blank=True, decimal_places=2, help_text='NULL means binary suggestion.', max_digits=12, null=True)),
                ('unit', models.CharField(blank=True, choices=[('kg', 'Kilogramos'), ('g', 'Gramos'), ('liters', 'Litros'), ('ml', 'Mililitros'), ('pieces', 'Piezas'), ('packages', 'Paquetes'), ('bags', 'Bolsas'), ('boxes', 'Cajas'), ('cans', 'Latas'), ('bottles', 'Botellas'), ('jugs', 'Garrafones'), ('trays', 'Charolas'), ('dozens', 'Docenas')], help_text='Required only if quantity_total is set.', max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_approval', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_event_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_suggestion_ref', to='items.eventitem')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='events.event')),
                ('reviewed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_suggestions', to=settings.AUTH_USER_MODEL)),
                ('suggested_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'item_suggestions',
                'indexes': [models.Index(fields=['event', 'status'], name='item_sugg_event_status_idx'), models.Index(fields=['suggested_by_user'], name='item_sugg_by_user_idx')],
            },
        ),
    ]
